name: CI

on: [push]

env:
  NODE_ENV: development

jobs:
  build:
    strategy:
      matrix:
        node: [16, 18, 20]

    runs-on: ubuntu-latest

    name: Validate on Node v${{ matrix.node }}

    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: yarn install

      - name: Bootstrap packages
        run: yarn lerna bootstrap

      - name: Flow
        run: yarn flow

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --runInBand
